# Configuration for training
results_root: "results"
split_type: "month"          # Options: "year", "month", "day"
range: "1"                  # Define the range value
project_name: "Apache"
start_year: 2000
end_year: 2004
start_month: 1              # Optional, required for "month" or "day" splits
end_month: 12               # Optional, required for "month" or "day" splits
start_day: 1                # Optional, required for "day" splits
end_day: 31                 # Optional, required for "day" splits

label_set:                     # Specify which labels to include
  - bug
  - feature

use_validation: false        # Whether to use a validation set
split_size: 0.3             # Size of the validation split (if use_validation is true)

model_type: setfit
sentence_transformer_model: all-MiniLM-L6-v2
sampling_strategy: random  # Options: random, balanced, stratified
samples_per_class: 50
sampling_seed: 42

# SetFit trainer args
setfit_args:
  num_iterations: 20
  num_epochs: 1

presaved_model_path: "results/Apache/setfit/year_range_1/2000_2004/model"